using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Deathmatch
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostDeathmatchLobbiesWindow : DefaultWindow
    {
        public event Action? SpawnButtonPressed;
        public GhostDeathmatchLobbiesWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
