using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Client.Graphics;


namespace Content.Client.UserInterface.Systems.Ghost.Controls.Deathmatch
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostDeathmatchLobbiesHeader : Control
    {

        public GhostDeathmatchLobbiesHeader()
        {
            RobustXamlLoader.Load(this);
        }

        public enum Header
        {
            Host,
            Map
        }
    }
}
